name: "Test Plugin"
on:
  pull_request: 
  workflow_dispatch: 
  push:
    tags-ignore:
      - 'v*'
    paths-ignore: 
      - .github/workflows/*
      - README.md
      - assets/*
env:
  PYTHON_VER: 3.8
jobs:
  deps:
    name: "Python"
    runs-on: windows-latest
    strategy:
      matrix:
        python_ver: [3.6, 3.7, 3.8, 3.9, 3.10]
    steps:
      - name: Get latest Version tag
        run: |
          $tag_name = (Invoke-WebRequest -Uri "https://api.github.com/repos/Flow-Launcher/Flow.Launcher/releases/latest" | ConvertFrom-Json).tag_name
          echo "LATEST_TAG=$tag_name" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Load Cache
        uses: actions/cache@v2
        id: flow_cache
        if: startsWith(runner.os, 'Windows')
        with:
          path: |
            ~\AppData\Roaming\FlowLauncher\*
            !~\AppData\Roaming\FlowLauncher\Plugins\*
            ~\AppData\Local\FlowLauncher\**
          key: ${{ runner.os }}-flow-${{ env.LATEST_TAG }}
      - name: Download Flow Launcher ${{ env.LATEST_TAG }}
        id: download
        if: steps.flow_cache.outputs.cache-hit != 'true'
        run: |
          curl.exe -L -o Flow-Launcher-Setup.exe "https://github.com/Flow-Launcher/Flow.Launcher/releases/download/${{env.LATEST_TAG}}/Flow-Launcher-Setup.exe"
      - name: Install Flow Launcher
        if: steps.flow_cache.outputs.cache-hit != 'true'
        run: .\Flow-Launcher-Setup.exe
        shell: cmd
      - name: Checkout Plugin Repo
        uses: actions/checkout@v2
        with:
          path: ${{github.event.repository.name}}
      - name: Move checkout repo
        run: |
          $repo_path = Join-Path -Path $pwd -ChildPath ${{github.event.repository.name}}
          $plugin_path = Join-Path -Path $env:APPDATA -ChildPath 'FlowLauncher' | Join-Path -ChildPath 'Plugins' | Join-Path -ChildPath ${{github.event.repository.name}}
          if (Test-Path $plugin_path)
          {
            echo "Removing cached directory"
            Remove-Item $plugin_path
          }
          New-Item -ItemType SymbolicLink -Path $plugin_path -Target $repo_path
          echo "PLUGIN_PATH=$plugin_path" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          cd ${{ env.PLUGIN_PATH }}
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r ./requirements.txt -t ./lib
      - name: Get Plugin's Execute file
        id: exe
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: '${{ env.PLUGIN_PATH }}/plugin.json'
          prop_path: 'ExecuteFileName'
      - name: Test Run
        run: |
          cd ${{ env.PLUGIN_PATH }}
          python ${{steps.exe.outputs.prop}}
